hideManual: true
watch:
  directories:
    - src
    - tests
  fileMask: '*.php'
notifications:
  passingTests: false
  failingTests: false
  
phpunit:
  binaryPath: C:\Users\Acer\AppData\Roaming\Composer\vendor\bin\phpunit.bat
  arguments: ' --bootstrap .\Core\Autoloader.php --testdox --colors=always '